### ISSUE TITLE
Missing files in tarball 

### ISSUE THREAD

**Issue by ewout** [johnhw/funnelplot#2]
The[ current tarbal on PyPy](https://files.pythonhosted.org/packages/a6/20/6047b6f3c9f7ce57ef67fadf37c3f2e36e11f6b7f003c5736bea0ff976c2/funnelplot-0.2.0.tar.gz) seems to be missing essential files, like settings.ini, that cause `pip install funnelplot` to fail.

`pip install git+https://github.com/johnhw/funnelplot` worked, though

**Comment by johnhw** [comment]
I think this is fixed with 0.2.1 on PyPI. Let me know if there are still install issues
